sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t lukicalk/docker-react -f Dockerfile.dev .

script:
  - docker run lukicalk/docker-react npm run test -- --coverage

#script:
# - docker run -e CI=true lukicalk/docker-react npm run test